---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-dumper
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          nodeSelector: 
            nodegroup-type: db-node-group
            instance-type: onDemand  
          restartPolicy: OnFailure
          containers:
          - name: postgres-dumper
            image: giutech/database-dumper
            imagePullPolicy: Always
            env:
            - name: DB_USER:
              value: giustech_username
            - name: DB_PASSWORD:
              value: giustech_username_dsv
            - name: DB_HOST:
              value: dbpostgres
            - name: DB_PORT:
              value: "5432"
            - name: DB_NAME:
              value: giustech_db
            - name: AWS_ACCESS_KEY_ID:
              value: AWS_S3_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY:
              value: AWS_S3_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION:
              value: AWS_DEFAULT_REGION
            - name: AWS_BUCKET:
              value: AWS_BUCKET
            - name: DUMPER_DIALECT:
              value: postgres
            - name: MAX_SNAPSHOTS:
              value: "3"